// <auto-generated />
namespace MessagingBoard.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class amen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(amen));
        
        string IMigrationMetadata.Id
        {
            get { return "201506070732395_amen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
